version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: api_blog
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/api-blog
    env_file:
      - .env

  frontend:
    build:
      context: ../frontend
    container_name: app_frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    env_file:
      - ../frontend/.env.docker
