version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: api_blog
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/api-blog

volumes:
  mongo_data:
