name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
       DOCKER_USERNAME: gp33postech
       DOCKER_PASSWORD: gp33postech@2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for MongoDB to start
        run: |
          docker login -u gp33postech -p gp33postech@2025
          docker build -t gp33postech/api_blog:latest .
          docker push gp33postech/api_blog:latest
